// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyApjckWcJtX1WbUOBm3gr01UxBCqDrBAt8',
    appId: '1:203230076023:web:077cb6de83ea8e468c3a72',
    messagingSenderId: '203230076023',
    projectId: 'project-f785f',
    authDomain: 'project-f785f.firebaseapp.com',
    storageBucket: 'project-f785f.appspot.com',
    measurementId: 'G-KJ1JXEYDDN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCjPBQJuvJ3T-9S3TSk4zRM50HaN9LZP8g',
    appId: '1:203230076023:android:4146b67aa4afa9d28c3a72',
    messagingSenderId: '203230076023',
    projectId: 'project-f785f',
    storageBucket: 'project-f785f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDo87AAS9BFeXj4LGH9qhoraVVr-JpCBLQ',
    appId: '1:203230076023:ios:45fae1f169a5a0e78c3a72',
    messagingSenderId: '203230076023',
    projectId: 'project-f785f',
    storageBucket: 'project-f785f.appspot.com',
    iosBundleId: 'com.example.watchshop',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDo87AAS9BFeXj4LGH9qhoraVVr-JpCBLQ',
    appId: '1:203230076023:ios:45fae1f169a5a0e78c3a72',
    messagingSenderId: '203230076023',
    projectId: 'project-f785f',
    storageBucket: 'project-f785f.appspot.com',
    iosBundleId: 'com.example.watchshop',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyApjckWcJtX1WbUOBm3gr01UxBCqDrBAt8',
    appId: '1:203230076023:web:73f04f37e2a00f478c3a72',
    messagingSenderId: '203230076023',
    projectId: 'project-f785f',
    authDomain: 'project-f785f.firebaseapp.com',
    storageBucket: 'project-f785f.appspot.com',
    measurementId: 'G-EW2LB9F5M3',
  );
}
